k9s:
  cluster: default
  skin: catppuccin-mocha-transparent
  namespace:
    active: rook-ceph
    lockFavorites: false
    favorites:
    - external-dns
    - all
    - default
    - rook-ceph
    - ingress-nginx
    - kube-system
    - argocd
    - plex
    - kindle-weather
    - frigate
    - sealed-secrets
    - metallb-system
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
